openapi: 3.0.1
info:
  title: Your API
  description: API description
  version: 1.0.0
servers:
  - url: http://api.drugguardian.net
components:
  securitySchemes:
    NegotiateAuth:
      type: http
      scheme: bearer
      bearerFormat: Negotiate
paths:
  /token:
    get:
      summary: Endpoint requiring Negotiate (Kerberos) authentication
      security:
        - NegotiateAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Success"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
security:
  - NegotiateAuth: []
